# NumPy-Numerical Python

### **numpy is extremely popular Python module. It is haevily used in scientific computing**

**numpy's most  useful faeture is `n dimentional arry` object (a.k.a ndarray**

In [1]:
import numpy as np
import time
import sys

In [2]:
a=np.array([1,2,5])
a

array([1, 2, 5])

### 3 main benefit of numpy array over a python list,

    1) Less memory
    2) Fast
    3) Convinient


In [3]:
l=range(1000)
print(sys.getsizeof(1)*len(l))

array=np.arange(1000)
print(array.size*array.itemsize)


28000
4000


In [4]:
len(l)

1000

In [5]:
l

range(0, 1000)

In [6]:
array.itemsize

4

In [7]:
sys.getsizeof(1)

28

In [8]:
l1=range(1000000)
l2=range(1000000)


a1=np.arange(1000000)
a2=np.arange(1000000)

#python list
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Python list took :", (time.time()-start)*1000)
      
#numpy array
start=time.time()
result=a1+a2
print("Numpy  took :", (time.time()-start)*1000)
      

Python list took : 191.4815902709961
Numpy  took : 18.945932388305664


In [9]:
%time
l=[1,2,3]
l2=[1,2,3]
k=[]
for i in range(len(l)):
    k.append(l[i]+l1[i])
print(k)

Wall time: 0 ns
[1, 3, 5]


In [10]:
%time result=[(x+y) for x,y in zip(l,l1)]
result

Wall time: 1.03 ms


[1, 3, 5]

## numpy : basic array operations

In [11]:
a=np.array([5,8,6])
a[0]

5

In [12]:
a[1]

8

In [13]:
a[2]

6

In [14]:
a=np.array([[1,2],[7,8],[5,6]])

### *ndim use to see the dimension of array

In [15]:
a.ndim

2

In [16]:
b=np.array([5,8,6])
b.ndim

1

### *itemsize use to print the byte size like int have 4 byte float have 8

### * dtype use to print type

In [17]:
a.itemsize

4

In [18]:
a.dtype

dtype('int32')

In [19]:
a=np.array([[1,2],[7,8],[5,6]],dtype=np.float64)

In [20]:
a.itemsize

8

In [21]:
a.dtype

dtype('float64')

### Size -- total  no.  in array

In [22]:
a.size

6

In [23]:
a

array([[1., 2.],
       [7., 8.],
       [5., 6.]])

### shape (row , column)

In [24]:
a.shape

(3, 2)

 numpy such as array properties (ndim, shape, itemsize, size etc.), math operations (min, max, sqrt, std etc.) arange, reshape etc.

In [25]:
a=np.array([[1,2],[7,8],[5,6]],dtype=complex)

In [26]:
a

array([[1.+0.j, 2.+0.j],
       [7.+0.j, 8.+0.j],
       [5.+0.j, 6.+0.j]])

In [27]:
a=np.array([[1,2],[7,8],[5,6]])

## np.zeros ((r x c)) use to create a nxn dim array with 0

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.ones ((r x c)) use to create a nxn dim array with 1

In [29]:
one=np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
one.dtype

dtype('float64')

## range in numpy is np.arange(start,end,step)

In [31]:
l=range(5)
l

range(0, 5)

In [32]:
l[0]

0

In [33]:
l[1]

1

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(1,5)

array([1, 2, 3, 4])

In [36]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### np.linspace(start, end, or between kitna num chahiye num=10)


**used to generate num between**

In [37]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [38]:
np.linspace(1,7,5)

array([1. , 2.5, 4. , 5.5, 7. ])

In [39]:
np.linspace(1,7,20)

array([1.        , 1.31578947, 1.63157895, 1.94736842, 2.26315789,
       2.57894737, 2.89473684, 3.21052632, 3.52631579, 3.84210526,
       4.15789474, 4.47368421, 4.78947368, 5.10526316, 5.42105263,
       5.73684211, 6.05263158, 6.36842105, 6.68421053, 7.        ])

# reshape(nxc) any dimension

In [40]:
a.shape

(3, 2)

In [41]:
a

array([[1, 2],
       [7, 8],
       [5, 6]])

In [42]:
a.reshape(2,3)

array([[1, 2, 7],
       [8, 5, 6]])

In [43]:
a.reshape(6,1)

array([[1],
       [2],
       [7],
       [8],
       [5],
       [6]])

In [44]:
a.reshape(6,10)

ValueError: cannot reshape array of size 6 into shape (6,10)

## ravel used to flaten a array (rxc) to n it give new array

In [45]:
a.ravel()

array([1, 2, 7, 8, 5, 6])

In [46]:
a

array([[1, 2],
       [7, 8],
       [5, 6]])

# Mathametical function

In [47]:
a.min()

1

In [48]:
a.max()

8

In [49]:
a.sum()

29

In [50]:
a.sum(axis=0)

array([13, 16])

In [51]:
a.sum(axis=1)

array([ 3, 15, 11])

In [52]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.64575131, 2.82842712],
       [2.23606798, 2.44948974]])

In [53]:
a

array([[1, 2],
       [7, 8],
       [5, 6]])

In [54]:
np.std(a)

2.544056253745625

In [55]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [56]:
a

array([[1, 2],
       [3, 4]])

In [57]:
b

array([[5, 6],
       [7, 8]])

In [58]:
a+b

array([[ 6,  8],
       [10, 12]])

In [59]:
a*b

array([[ 5, 12],
       [21, 32]])

In [60]:
a-b

array([[-4, -4],
       [-4, -4]])

In [61]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [62]:
a.dot(b)

array([[19, 22],
       [43, 50]])

### numpy array operations such as slicing, indexing, stacking. We will also go over how to index one array with another boolean array.


In [63]:
n=[6,7,8]

In [64]:
n[0:2]

[6, 7]

In [65]:
n[-1]

8

In [66]:
a=np.array([6,7,8])

In [67]:
a[0:2]

array([6, 7])

In [68]:
a[-1]

8

In [77]:
a=np.array([[1,2,8],[7,8,6],[5,6,3]])

In [78]:
a

array([[1, 2, 8],
       [7, 8, 6],
       [5, 6, 3]])

In [80]:
a[2,2]#  (r,c)

3

In [81]:
a[1,0]

7

In [82]:
a[1,0:2]

array([7, 8])

In [83]:
a[1,0:-1]

array([7, 8])

In [84]:
a[1,0:3]

array([7, 8, 6])

In [85]:
a[-1]

array([5, 6, 3])

In [86]:
a[0]

array([1, 2, 8])

In [87]:
a[1]

array([7, 8, 6])

In [95]:
a[2][1]

6

In [89]:
a

array([[1, 2, 8],
       [7, 8, 6],
       [5, 6, 3]])

In [98]:
a[:,1:3]

array([[2, 8],
       [8, 6],
       [6, 3]])

In [99]:
a

array([[1, 2, 8],
       [7, 8, 6],
       [5, 6, 3]])

In [102]:
for i in a:
    print(i)

[1 2 8]
[7 8 6]
[5 6 3]


In [103]:
for cell in a.flat:
    print(cell)

1
2
8
7
8
6
5
6
3


# flat use to flat array

In [111]:
a.flat[:]

array([1, 2, 8, 7, 8, 6, 5, 6, 3])

In [115]:
a.ravel()

array([1, 2, 8, 7, 8, 6, 5, 6, 3])

In [117]:
for cell in a.ravel():
    print(cell)

1
2
8
7
8
6
5
6
3


## Full() used to fill the array

In [120]:
b=np.full((3,4),5)

In [121]:
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

# Joining Numpy Array

In [128]:
a=np.arange(6).reshape(3,2)

In [129]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [130]:
b=np.arange(6,12).reshape(3,2)

In [131]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

## vstack()  vertical stack  ---row_stack both same

In [132]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [135]:
np.row_stack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## hstack()----column_stack both same

In [133]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [134]:
np.column_stack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

# vsplit and hsplit split tha array

In [149]:
a=np.arange(30).reshape(3,10)

In [150]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [167]:
np.hsplit(a,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29]])]

In [165]:
np.vsplit(a,3)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

# indexing with boolean array

In [168]:
a=np.arange(12).reshape(3,4)

In [169]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
b=a>4

In [171]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [172]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [173]:
a[b]=-1

In [174]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [175]:
b=a==-1

In [176]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

# numpy's loadtxt and savetxt

In [178]:
a=np.arange(15).reshape(3,5)

In [179]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [180]:
np.save("my_numpy",a)

In [181]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [182]:
n2=np.load("my_numpy.npy")

In [183]:
n2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [184]:
np.savetxt("test.txt",a)

# Numpy Intersection & Difference

In [198]:
n1=np.array([10,20,30,40,50])
n2=np.array([40,50,60,70,80])

In [199]:
np.intersect1d(n1,n2)

array([40, 50])

In [200]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [201]:
np.setdiff1d(n2,n1)

array([60, 70, 80])

# Numpy Array Mathematic

In [202]:
n1+n2

array([ 50,  70,  90, 110, 130])

In [204]:
np.sum((n1,n2))

450

In [205]:
np.sum((n1,n2),axis=0)# 0= col

array([ 50,  70,  90, 110, 130])

In [207]:
np.sum((n1,n2),axis=1)# 1= row

array([150, 300])

In [210]:
np.subtract(n1,n2)

array([-30, -30, -30, -30, -30])

In [211]:
n1*2

array([ 20,  40,  60,  80, 100])

In [212]:
n1+2

array([12, 22, 32, 42, 52])

In [213]:
n1-2

array([ 8, 18, 28, 38, 48])

In [214]:
n1/2

array([ 5., 10., 15., 20., 25.])

In [216]:
np.mean(n1)

30.0

In [218]:
np.median(n2)

60.0

In [229]:
a=np.arange(12).reshape(3,4)

In [233]:
b=a<6

In [234]:
a[b]

array([0, 1, 2, 3, 4, 5])

In [235]:
b

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [237]:
a[b]=6

In [238]:
a

array([[ 6,  6,  6,  6],
       [ 6,  6,  6,  7],
       [ 8,  9, 10, 11]])

In [243]:
a.mode()   # scipy mai hai numpy 

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [245]:
np.unique(a)

array([ 6,  7,  8,  9, 10, 11])

# iterate numpy array using nditer 

In [4]:

a=np.arange(12).reshape(3,4)

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for i in a.flatten():
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
for i in np.nditer(a,order="C"):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
for i in np.nditer(a,order="F"):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


# take_along_axis(x,y,1)

In [14]:
x=np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
x=x*2.1

In [18]:
x

array([[ 0. ,  2.1,  4.2,  6.3,  8.4],
       [10.5, 12.6, 14.7, 16.8, 18.9],
       [21. , 23.1, 25.2, 27.3, 29.4],
       [31.5, 33.6, 35.7, 37.8, 39.9],
       [42. , 44.1, 46.2, 48.3, 50.4]])

In [19]:
y=np.array([[3,0,1,2,4],
            [4,0,1,3,2],
            [2,0,4,3,1],
            [3,4,2,0,1],
            [4,3,2,0,1]])

In [20]:
y

array([[3, 0, 1, 2, 4],
       [4, 0, 1, 3, 2],
       [2, 0, 4, 3, 1],
       [3, 4, 2, 0, 1],
       [4, 3, 2, 0, 1]])

In [21]:
np.take_along_axis(x,y,1)

array([[ 6.3,  0. ,  2.1,  4.2,  8.4],
       [18.9, 10.5, 12.6, 16.8, 14.7],
       [25.2, 21. , 29.4, 27.3, 23.1],
       [37.8, 39.9, 35.7, 31.5, 33.6],
       [50.4, 48.3, 46.2, 42. , 44.1]])

In [28]:
x.shape[0]

5

In [25]:
np.arange(x.shape[0])[:,None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [35]:
x[np.arange(x.shape[0])[:,None],0]

array([[ 0. ],
       [10.5],
       [21. ],
       [31.5],
       [42. ]])

In [32]:
x[np.arange(x.shape[0])[:,None],y]

array([[ 6.3,  0. ,  2.1,  4.2,  8.4],
       [18.9, 10.5, 12.6, 16.8, 14.7],
       [25.2, 21. , 29.4, 27.3, 23.1],
       [37.8, 39.9, 35.7, 31.5, 33.6],
       [50.4, 48.3, 46.2, 42. , 44.1]])

In [38]:
b=np.empty((0,3),int)

In [39]:
np.append(b,np.array([[4,8,6]]),axis=0)

array([[4, 8, 6]])

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
np.split(a,(2,5))

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([], shape=(0, 4), dtype=int32)]

In [47]:
np.where(a>6)

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [51]:
a=np.arange(20)

In [52]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
np.where(a>6)

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

In [54]:
np.where(a>6,"A","B")

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [55]:
np.delete(a,8)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [56]:
np.delete(a,[4,6,8,2,7])

array([ 0,  1,  3,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [61]:
b=np.arange(12).reshape(3,4)

In [62]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
np.delete(b,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
np.delete(b,2,axis=None)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
np.delete(b,[1,3])

array([ 0,  2,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
np.delete(b,1,axis=1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [72]:
np.delete(b,0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
np.delete(b,0,axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
np.delete(b,[0,-1],axis=1)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [75]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
np.delete(b,[0,-1],axis=0)

array([[4, 5, 6, 7]])

In [79]:
np.extract(b%2==0,b)

array([ 0,  2,  4,  6,  8, 10])

In [80]:
np.extract(b%2!=0,b)

array([ 1,  3,  5,  7,  9, 11])

In [82]:
sum(b)

array([12, 15, 18, 21])

In [83]:
import sys

In [84]:
np.set_printoptions(threshold=sys.maxsize)

In [85]:
np.arange(5000)

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1

In [86]:
np.set_printoptions(threshold=3)